language: ruby
rvm:
  - 1.9.3
script: bundle exec rspec spec
bundler_args: "--without development"
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database bingo_test;' -U postgres