development:
  adapter: postgresql
  encoding: unicode
  database: bingo_development
  pool: 5
  username: bingo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bingo_test
  pool: 5
  username: bingo
  password:

postgres:
  adapter: postgresql
  database: bingo_test
  username: postgres
